# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='service english name', max_length=40, verbose_name='Service_name')),
                ('name_persian', models.CharField(max_length=40, verbose_name='service_name_persian')),
                ('service_id', models.CharField(max_length=20)),
                ('service_id_free', models.CharField(max_length=20)),
                ('short_code', models.CharField(max_length=20)),
                ('short_code_free', models.CharField(max_length=20)),
                ('subscribe_keyword', models.CharField(max_length=20)),
                ('unsubscribe_keyword', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mo_url', models.CharField(max_length=300)),
                ('unsubscribe_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udated_at', models.DateTimeField(auto_now_add=True)),
                ('enable', models.BooleanField()),
                ('help_messge_visible', models.BooleanField()),
                ('wsdl_visible', models.BooleanField()),
                ('report_visible', models.BooleanField()),
            ],
        ),
    ]
