# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20160416_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('subscribe', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('user_deleted_key', models.BooleanField(default=False, verbose_name='deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udated_at', models.DateTimeField(auto_now_add=True)),
                ('city_code', models.CharField(max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Service')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('mobile', 'service')]),
        ),
    ]
